Repository avast/retdec, pull requests merged in 2020-11, with the labels that each got.

#894 Fix missing comma in usualPackerSections initializer
  src/fileformat/file_format/pe/pe_format.cpp
Labels: C-cpdetect, bug

#897 Lz import thunk check
  include/retdec/pelib/ImportDirectory.h
Labels: C-fileinfo, bug

#899 Added YARA rule for Inno Setup 6.0.0
  support/yara_patterns/tools/pe/x86/installers.yara
Labels: C-cpdetect, enhancement
