Repository avast/retdec, pull requests merged in 2020-04, with the labels that each got.

#733 Check for Armadillo made more generic
  src/cpdetect/compiler_detector/heuristics/pe_heuristics.cpp
Labels: C-cpdetect, enhancement

#735 Added tests for more versions of Petite packer
  support/yara_patterns/tools/pe/x86/packers.yara
Labels: C-cpdetect, enhancement

#734 Add detection support for newer versions of VMProtect.
  include/retdec/fileformat/types/sec_seg/sec_seg.h
  src/cpdetect/compiler_detector/heuristics/pe_heuristics.cpp
  support/yara_patterns/tools/pe/x86/packers.yara
Labels: C-cpdetect, enhancement

#741 Improve the detection of Enigma protector (32-bit).
  support/yara_patterns/tools/pe/x64/packers.yara
  support/yara_patterns/tools/pe/x86/packers.yara
Labels: C-cpdetect, enhancement

#743 Improve the detection of ASPack executable packer.
  support/yara_patterns/tools/pe/x86/packers.yara
Labels: C-cpdetect, enhancement

#745 Fixed missing <limits> header
  src/fileinfo/file_information/file_information_types/data_directory.h
  src/fileinfo/file_information/file_information_types/dynamic_section/dynamic_entry.h
  src/fileinfo/file_information/file_information_types/file_header.h
  src/fileinfo/file_information/file_information_types/file_section.h
  src/fileinfo/file_information/file_information_types/file_segment.h
  src/fileinfo/file_information/file_information_types/pattern/pattern_match.h
  src/fileinfo/file_information/file_information_types/pdb_info.h
  src/fileinfo/file_information/file_information_types/relocation_table/relocation.h
  src/fileinfo/file_information/file_information_types/resource_table/resource.h
  src/fileinfo/file_information/file_information_types/symbol_table/symbol.h
Labels: P-build, enhancement

#748 Added detection of PyInstaller
  src/cpdetect/compiler_detector/compiler_detector.cpp
  support/yara_patterns/tools/pe/x64/installers.yara
  support/yara_patterns/tools/pe/x86/installers.yara
Labels: C-cpdetect, enhancement

#749 Add support for using the 'dotnet' module in YARA rules
  CHANGELOG.md
  deps/yara/CMakeLists.txt
  deps/yara/patch.cmake
  include/retdec/cpdetect/compiler_detector/coff_compiler.h
  include/retdec/cpdetect/compiler_detector/compiler_detector.h
  include/retdec/cpdetect/compiler_detector/elf_compiler.h
  include/retdec/cpdetect/compiler_detector/intel_hex_compiler.h
  include/retdec/cpdetect/compiler_detector/macho_compiler.h
  include/retdec/cpdetect/compiler_detector/pe_compiler.h
  include/retdec/cpdetect/compiler_detector/raw_data_compiler.h
  include/retdec/cpdetect/compiler_detector/search/search.h
  include/retdec/cpdetect/compiler_factory.h
  include/retdec/cpdetect/cpdetect.h
  include/retdec/cpdetect/cptypes.h
  include/retdec/cpdetect/heuristics/elf_heuristics.h
  include/retdec/cpdetect/heuristics/heuristics.h
  include/retdec/cpdetect/heuristics/macho_heuristics.h
  include/retdec/cpdetect/heuristics/pe_heuristics.h
  include/retdec/cpdetect/search.h
  include/retdec/cpdetect/settings.h
  include/retdec/cpdetect/signature.h
  include/retdec/cpdetect/signatures/avg/signature.h
  include/retdec/cpdetect/signatures/avg/signature_checker.h
  include/retdec/cpdetect/utils/version_solver.h
  include/retdec/utils/string.h
  src/cpdetect/CMakeLists.txt
  src/cpdetect/compiler_detector/coff_compiler.cpp
  src/cpdetect/compiler_detector/elf_compiler.cpp
  src/cpdetect/compiler_detector/intel_hex_compiler.cpp
  src/cpdetect/compiler_detector/macho_compiler.cpp
  src/cpdetect/compiler_detector/pe_compiler.cpp
  src/cpdetect/compiler_detector/raw_data_compiler.cpp
  src/cpdetect/compiler_factory.cpp
  src/cpdetect/cpdetect.cpp
  src/cpdetect/cptypes.cpp
  src/cpdetect/errors.cpp
  src/cpdetect/heuristics/elf_heuristics.cpp
  src/cpdetect/heuristics/heuristics.cpp
  src/cpdetect/heuristics/macho_heuristics.cpp
  src/cpdetect/heuristics/pe_heuristics.cpp
  src/cpdetect/search.cpp
  src/cpdetect/signature.cpp
  src/cpdetect/signatures/avg/signature.cpp
  src/cpdetect/signatures/avg/signature_checker.cpp
  src/cpdetect/utils/version_solver.cpp
  src/fileinfo/file_detector/coff_detector.cpp
  src/fileinfo/file_detector/elf_detector.cpp
  src/fileinfo/file_detector/intel_hex_detector.cpp
  src/fileinfo/file_detector/intel_hex_detector.h
  src/fileinfo/file_detector/macho_detector.cpp
  src/fileinfo/file_detector/pe_detector.cpp
  src/fileinfo/file_detector/raw_data_detector.cpp
  src/fileinfo/file_detector/raw_data_detector.h
  src/unpackertool/unpacker.cpp
  src/utils/string.cpp
  support/yara_patterns/tools/pe/x86/packers.yara
  tests/utils/string_tests.cpp
Labels: C-yara, enhancement

#753 Add detection support of Astrum InstallWizard.
  support/yara_patterns/tools/pe/x86/installers.yara
Labels: C-cpdetect, enhancement

#756 Add detection of AutoHotKey compiler.
  support/yara_patterns/tools/pe/x64/compilers.yara
  support/yara_patterns/tools/pe/x86/compilers.yara
Labels: C-cpdetect, enhancement

#757 Improve the detection of AutoIT files compiled to binary.
  support/yara_patterns/tools/pe/x64/compilers.yara
  support/yara_patterns/tools/pe/x86/compilers.yara
Labels: C-cpdetect, enhancement
